In [1]:
from config import EIA_APP_KEY
import requests
import json
from pprint import pprint
import pandas as pd
import pymongo

In [20]:
# Datasource #1: Read CSV to get annual generation of Electricity in US all sectors

filename = "./Resources/Net_generation_United_States_all_sectors_annual.csv"
df_annual_allstates = pd.read_csv(filename)

df_annual_allstates.head(20)

,Year,all fuels (utility-scale) thousand megawatthours,coal thousand megawatthours,natural gas thousand megawatthours,nuclear thousand megawatthours,conventional hydroelectric thousand megawatthours,wind thousand megawatthours,all solar thousand megawatthours
0,2017,4034268.431,1205835.275,1.296415e+06,804949.6350,300333.1555,254302.66190,77276.45872
1,2016,4076674.984,1239148.654,1.378307e+06,805693.9480,267812.1531,226992.56210,54866.49178
2,2015,4077600.939,1352398.197,1.333482e+06,797177.8770,249080.0848,190718.54770,39032.17088
3,2014,4093606.005,1581710.350,1.126609e+06,797165.9820,259366.6219,181655.28180,28923.68989
4,2013,4065964.067,1581114.716,1.124836e+06,789016.4730,268565.3827,167839.74540,NaN
5,2012,4047765.267,1514042.945,1.225894e+06,769331.2490,276240.2193,140821.71470,NaN
6,2011,4100140.926,1733430.005,1.013689e+06,790204.3670,319354.9035,120176.59860,NaN
7,2010,4125059.899,1847290.279,9.876972e+05,806968.3006,260203.0694,94652.24608,NaN
8,2009,3950330.926,1755904.253,9.209787e+05,798854.5850,273445.0942,73886.13171,NaN
9,2008,4119387.760,1985801.247,8.829806e+05,806208.4350,254831.3851,55363.10007,NaN
10,2007,4156744.724,2016455.584,8.965898e+05,806424.7530,247509.9743,34449.92740,NaN
11,2006,4064702.227,1990511.135,8.164408e+05,787218.6360,289246.4157,26589.13699,NaN
12,2005,4055422.750,2012873.046,7.609603e+05,781986.3650,270321.2549,17810.54902,NaN
13,2004,3970555.263,1978300.549,7.101000e+05,788528.3870,268417.3084,14143.74074,NaN
14,2003,3883185.205,1973736.750,6.499075e+05,763732.6950,275806.3280,11187.46700,NaN
15,2002,3858452.254,1933130.354,6.910057e+05,780064.0870,264328.8330,10354.27900,NaN
16,2001,3736643.653,1903955.943,6.391291e+05,768826.3080,216961.0440,6737.33200,NaN

In [2]:
# get EIA data using API key, returns a json object 
# print(EIA_APP_KEY)
def state_id_to_json(series_id):
    params = {
        "series_id": series_id, 
        "api_key": EIA_APP_KEY
    }

    target_url = ('http://api.eia.gov/series/')
    response = requests.get(target_url, params=params)
    electricity_results = response.json()
    return electricity_results

In [4]:
# for wind production - State wise
alaska_annual_wind = state_id_to_json('ELEC.GEN.WND-AK-99.A')
arizona_annual_wind = state_id_to_json('ELEC.GEN.WND-AZ-99.A')
cali_annual_wind = state_id_to_json('ELEC.GEN.WND-CA-99.A')
colorado_annual_wind = state_id_to_json('ELEC.GEN.WND-CO-99.A')
connecticut_annual_wind = state_id_to_json('ELEC.GEN.WND-CT-99.A')
delaware_annual_wind = state_id_to_json('ELEC.GEN.WND-DE-99.A')
hawaii_annual_wind = state_id_to_json('ELEC.GEN.WND-DE-HI.A')
idaho_annual_wind = state_id_to_json('ELEC.GEN.WND-ID-99.A')
illinois_annual_wind = state_id_to_json('ELEC.GEN.WND-IL-99.A')
indiana_annual_wind = state_id_to_json('ELEC.GEN.WND-IN-99.A')
iowa_annual_wind = state_id_to_json('ELEC.GEN.WND-IA-99.A')
kansas_annual_wind = state_id_to_json('ELEC.GEN.WND-KS-99.A')
maine_annual_wind = state_id_to_json('ELEC.GEN.WND-ME-99.A')
maryland_annual_wind = state_id_to_json('ELEC.GEN.WND-MD-99.A')
massa_annual_wind = state_id_to_json('ELEC.GEN.WND-MA-99.A')
michigan_annual_wind = state_id_to_json('ELEC.GEN.WND-MI-99.A')
minnesota_annual_wind = state_id_to_json('ELEC.GEN.WND-MN-99.A')
missouri_annual_wind = state_id_to_json('ELEC.GEN.WND-MO-99.A')
montana_annual_wind = state_id_to_json('ELEC.GEN.WND-MT-99.A')
neb_annual_wind = state_id_to_json('ELEC.GEN.WND-NB-99.A')
nevada_annual_wind = state_id_to_json('ELEC.GEN.WND-NV-99.A')
newHem_annual_wind = state_id_to_json('ELEC.GEN.WND-NH-99.A')
newJer_annual_wind = state_id_to_json('ELEC.GEN.WND-NJ-99.A')
newMex_annual_wind = state_id_to_json('ELEC.GEN.WND-NM-99.A')
newYork_annual_wind = state_id_to_json('ELEC.GEN.WND-NY-99.A')
norCaro_annual_wind = state_id_to_json('ELEC.GEN.WND-NC-99.A')
norDak_annual_wind = state_id_to_json('ELEC.GEN.WND-ND-99.A')
ohio_annual_wind = state_id_to_json('ELEC.GEN.WND-OH-99.A')
oklo_annual_wind = state_id_to_json('ELEC.GEN.WND-OK-99.A')
oregon_annual_wind = state_id_to_json('ELEC.GEN.WND-OR-99.A')
pennsil_annual_wind = state_id_to_json('ELEC.GEN.WND-PA-99.A')
rhodeIsland_annual_wind = state_id_to_json('ELEC.GEN.WND-RI-99.A')
souDak_annual_wind = state_id_to_json('ELEC.GEN.WND-SD-99.A')
ten_annual_wind = state_id_to_json('ELEC.GEN.WND-TN-99.A')
texas_annual_wind = state_id_to_json('ELEC.GEN.WND-TX-99.A')
utah_annual_wind = state_id_to_json('ELEC.GEN.WND-UT-99.A')
vermont_annual_wind = state_id_to_json('ELEC.GEN.WND-VT-99.A')
wash_annual_wind = state_id_to_json('ELEC.GEN.WND-WA-99.A')
westvir_annual_wind = state_id_to_json('ELEC.GEN.WND-WV-99.A')
wisc_annual_wind = state_id_to_json('ELEC.GEN.WND-WI-99.A')
wyom_annual_wind = state_id_to_json('ELEC.GEN.WND-WY-99.A')

pprint(wyom_annual_wind)

{'request': {'command': 'series', 'series_id': 'ELEC.GEN.WND-WY-99.A'},
 'series': [{'copyright': 'None',
             'data': [['2017', 4320.655],
                      ['2016', 4389.338],
                      ['2015', 3756.708],
                      ['2014', 4405.757],
                      ['2013', 4433.284],
                      ['2012', 4369.107],
                      ['2011', 4611.868],
                      ['2010', 3246.79304],
                      ['2009', 2226.20458],
                      ['2008', 962.542],
                      ['2007', 754.881],
                      ['2006', 759.061],
                      ['2005', 717.264],
                      ['2004', 616.515],
                      ['2003', 366.478],
                      ['2002', 447.33],
                      ['2001', 365.159]],
             'description': 'Wind powered electricity generation; All '
                            'sectors; ',
             'end': '2017',
             'f': 'A',
             'geography': 'USA-WY',
             'iso3166': 'USA-WY',
             'name': 'Net generation : wind : Wyoming : all sectors : annual',
             'series_id': 'ELEC.GEN.WND-WY-99.A',
             'source': 'EIA, U.S. Energy Information Administration',
             'start': '2001',
             'units': 'thousand megawatthours',
             'updated': '2018-12-24T15:04:35-0500'}]}

In [5]:
# for conventional hydroelectric production - State wise
alabama_annual_hyc = state_id_to_json('ELEC.GEN.HYC-AL-99.A')
alaska_annual_hyc = state_id_to_json('ELEC.GEN.HYC-AK-99.A')
arizona_annual_hyc = state_id_to_json('ELEC.GEN.HYC-AZ-99.A')
arkansa_annual_hyc = state_id_to_json('ELEC.GEN.HYC-AR-99.A')
cali_annual_hyc = state_id_to_json('ELEC.GEN.HYC-CA-99.A')
colorado_annual_hyc = state_id_to_json('ELEC.GEN.HYC-CO-99.A')
connecticut_annual_hyc = state_id_to_json('ELEC.GEN.HYC-CT-99.A')
florida_annual_hyc = state_id_to_json('ELEC.GEN.HYC-FL-99.A')
georgia_annual_hyc = state_id_to_json('ELEC.GEN.HYC-GA-99.A')
hawaii_annual_hyc = state_id_to_json('ELEC.GEN.HYC-DE-HI.A')
idaho_annual_hyc = state_id_to_json('ELEC.GEN.HYC-ID-99.A')
illinois_annual_hyc = state_id_to_json('ELEC.GEN.HYC-IL-99.A')
indiana_annual_hyc = state_id_to_json('ELEC.GEN.HYC-IN-99.A')
iowa_annual_hyc = state_id_to_json('ELEC.GEN.HYC-IA-99.A')
kansas_annual_hyc = state_id_to_json('ELEC.GEN.HYC-KS-99.A')
ken_annual_hyc = state_id_to_json('ELEC.GEN.HYC-KY-99.A')
lou_annual_hyc = state_id_to_json('ELEC.GEN.HYC-LA-99.A')
maine_annual_hyc = state_id_to_json('ELEC.GEN.HYC-ME-99.A')
maryland_annual_hyc = state_id_to_json('ELEC.GEN.HYC-MD-99.A')
massa_annual_hyc = state_id_to_json('ELEC.GEN.HYC-MA-99.A')
michigan_annual_hyc = state_id_to_json('ELEC.GEN.HYC-MI-99.A')
minnesota_annual_hyc = state_id_to_json('ELEC.GEN.HYC-MN-99.A')
missouri_annual_hyc = state_id_to_json('ELEC.GEN.HYC-MO-99.A')
montana_annual_hyc = state_id_to_json('ELEC.GEN.HYC-MT-99.A')
neb_annual_hyc = state_id_to_json('ELEC.GEN.HYC-NB-99.A')
nevada_annual_hyc = state_id_to_json('ELEC.GEN.HYC-NV-99.A')
newHem_annual_hyc = state_id_to_json('ELEC.GEN.HYC-NH-99.A')
newJer_annual_hyc = state_id_to_json('ELEC.GEN.HYC-NJ-99.A')
newMex_annual_hyc = state_id_to_json('ELEC.GEN.HYC-NM-99.A')
newYork_annual_hyc = state_id_to_json('ELEC.GEN.HYC-NY-99.A')
norCaro_annual_hyc = state_id_to_json('ELEC.GEN.HYC-NC-99.A')
norDak_annual_hyc = state_id_to_json('ELEC.GEN.HYC-ND-99.A')
ohio_annual_hyc = state_id_to_json('ELEC.GEN.HYC-OH-99.A')
oklo_annual_hyc = state_id_to_json('ELEC.GEN.HYC-OK-99.A')
oregon_annual_hyc = state_id_to_json('ELEC.GEN.HYC-OR-99.A')
pennsil_annual_hyc = state_id_to_json('ELEC.GEN.HYC-PA-99.A')
rhodeIsland_annual_hyc = state_id_to_json('ELEC.GEN.HYC-RI-99.A')
souCaro_annual_hyc = state_id_to_json('ELEC.GEN.HYC-SC-99.A')
souDak_annual_hyc = state_id_to_json('ELEC.GEN.HYC-SD-99.A')
ten_annual_hyc = state_id_to_json('ELEC.GEN.HYC-TN-99.A')
texas_annual_hyc = state_id_to_json('ELEC.GEN.HYC-TX-99.A')
utah_annual_hyc = state_id_to_json('ELEC.GEN.HYC-UT-99.A')
vermont_annual_hyc = state_id_to_json('ELEC.GEN.HYC-VT-99.A')
virginia_annual_hyc = state_id_to_json('ELEC.GEN.HYC-VA-99.A')
wash_annual_hyc = state_id_to_json('ELEC.GEN.HYC-WA-99.A')
westvir_annual_hyc = state_id_to_json('ELEC.GEN.HYC-WV-99.A')
wisc_annual_hyc = state_id_to_json('ELEC.GEN.HYC-WI-99.A')
wyom_annual_hyc = state_id_to_json('ELEC.GEN.HYC-WY-99.A')

pprint(wyom_annual_hyc)

{'request': {'command': 'series', 'series_id': 'ELEC.GEN.HYC-WY-99.A'},
 'series': [{'copyright': 'None',
             'data': [['2017', 1123.62359],
                      ['2016', 973.48819],
                      ['2015', 868.261],
                      ['2014', 868.71015],
                      ['2013', 710.87817],
                      ['2012', 893.47],
                      ['2011', 1223.73],
                      ['2010', 1023.887],
                      ['2009', 966.572],
                      ['2008', 835.275],
                      ['2007', 729.424],
                      ['2006', 843.316],
                      ['2005', 808.375],
                      ['2004', 593.14704],
                      ['2003', 593.555],
                      ['2002', 583.615],
                      ['2001', 879.111]],
             'description': 'Hydroelectric powered dams other than reversible '
                            'pumped storage; All sectors; ',
             'end': '2017',
             'f': 'A',
             'geography': 'USA-WY',
             'iso3166': 'USA-WY',
             'name': 'Net generation : conventional hydroelectric : Wyoming : '
                     'all sectors : annual',
             'series_id': 'ELEC.GEN.HYC-WY-99.A',
             'source': 'EIA, U.S. Energy Information Administration',
             'start': '2001',
             'units': 'thousand megawatthours',
             'updated': '2018-12-24T15:04:35-0500'}]}

In [6]:
# for solar production - State wise
alabama_annual_tsn = state_id_to_json('ELEC.GEN.TSN-AL-99.A')
alaska_annual_tsn = state_id_to_json('ELEC.GEN.TSN-AK-99.A')
arizona_annual_tsn = state_id_to_json('ELEC.GEN.TSN-AZ-99.A')
arkansa_annual_tsn = state_id_to_json('ELEC.GEN.TSN-AR-99.A')
cali_annual_tsn = state_id_to_json('ELEC.GEN.TSN-CA-99.A')
colorado_annual_tsn = state_id_to_json('ELEC.GEN.TSN-CO-99.A')
connecticut_annual_tsn = state_id_to_json('ELEC.GEN.TSN-CT-99.A')
delaware_annual_tsn = state_id_to_json('ELEC.GEN.TSN-DE-99.A')
florida_annual_tsn = state_id_to_json('ELEC.GEN.TSN-FL-99.A')
georgia_annual_tsn = state_id_to_json('ELEC.GEN.TSN-GA-99.A')
hawaii_annual_tsn = state_id_to_json('ELEC.GEN.TSN-DE-HI.A')
idaho_annual_tsn = state_id_to_json('ELEC.GEN.TSN-ID-99.A')
illinois_annual_tsn = state_id_to_json('ELEC.GEN.TSN-IL-99.A')
indiana_annual_tsn = state_id_to_json('ELEC.GEN.TSN-IN-99.A')
iowa_annual_tsn = state_id_to_json('ELEC.GEN.TSN-IA-99.A')
kansas_annual_tsn = state_id_to_json('ELEC.GEN.TSN-KS-99.A')
ken_annual_tsn = state_id_to_json('ELEC.GEN.TSN-KY-99.A')
lou_annual_tsn = state_id_to_json('ELEC.GEN.TSN-LA-99.A')
maine_annual_tsn = state_id_to_json('ELEC.GEN.TSN-ME-99.A')
maryland_annual_tsn = state_id_to_json('ELEC.GEN.TSN-MD-99.A')
massa_annual_tsn = state_id_to_json('ELEC.GEN.TSN-MA-99.A')
michigan_annual_tsn = state_id_to_json('ELEC.GEN.TSN-MI-99.A')
minnesota_annual_tsn = state_id_to_json('ELEC.GEN.TSN-MN-99.A')
missis_annual_tsn = state_id_to_json('ELEC.GEN.TSN-MS-99.A')
missouri_annual_tsn = state_id_to_json('ELEC.GEN.TSN-MO-99.A')
montana_annual_tsn = state_id_to_json('ELEC.GEN.TSN-MT-99.A')
neb_annual_tsn = state_id_to_json('ELEC.GEN.TSN-NB-99.A')
nevada_annual_tsn = state_id_to_json('ELEC.GEN.TSN-NV-99.A')
newHem_annual_tsn = state_id_to_json('ELEC.GEN.TSN-NH-99.A')
newJer_annual_tsn = state_id_to_json('ELEC.GEN.TSN-NJ-99.A')
newMex_annual_tsn = state_id_to_json('ELEC.GEN.TSN-NM-99.A')
newYork_annual_tsn = state_id_to_json('ELEC.GEN.TSN-NY-99.A')
norCaro_annual_tsn = state_id_to_json('ELEC.GEN.TSN-NC-99.A')
norDak_annual_tsn = state_id_to_json('ELEC.GEN.TSN-ND-99.A')
ohio_annual_tsn = state_id_to_json('ELEC.GEN.TSN-OH-99.A')
oklo_annual_tsn = state_id_to_json('ELEC.GEN.TSN-OK-99.A')
oregon_annual_tsn = state_id_to_json('ELEC.GEN.TSN-OR-99.A')
pennsil_annual_tsn = state_id_to_json('ELEC.GEN.TSN-PA-99.A')
rhodeIsland_annual_tsn = state_id_to_json('ELEC.GEN.TSN-RI-99.A')
souCaro_annual_tsn = state_id_to_json('ELEC.GEN.TSN-SC-99.A')
souDak_annual_tsn = state_id_to_json('ELEC.GEN.TSN-SD-99.A')
ten_annual_tsn = state_id_to_json('ELEC.GEN.TSN-TN-99.A')
texas_annual_tsn = state_id_to_json('ELEC.GEN.TSN-TX-99.A')
utah_annual_tsn = state_id_to_json('ELEC.GEN.TSN-UT-99.A')
vermont_annual_tsn = state_id_to_json('ELEC.GEN.TSN-VT-99.A')
virginia_annual_tsn = state_id_to_json('ELEC.GEN.TSN-VA-99.A')
wash_annual_tsn = state_id_to_json('ELEC.GEN.TSN-WA-99.A')
westvir_annual_tsn = state_id_to_json('ELEC.GEN.TSN-WV-99.A')
wisc_annual_tsn = state_id_to_json('ELEC.GEN.TSN-WI-99.A')
wyom_annual_tsn = state_id_to_json('ELEC.GEN.TSN-WY-99.A')

pprint(westvir_annual_tsn)

{'request': {'command': 'series', 'series_id': 'ELEC.GEN.TSN-WV-99.A'},
 'series': [{'copyright': 'None',
             'data': [['2017', 7.89907],
                      ['2016', 5.66117],
                      ['2015', 4.47981],
                      ['2014', 3.64191]],
             'description': 'All sectors; ',
             'end': '2017',
             'f': 'A',
             'geography': 'USA-WV',
             'iso3166': 'USA-WV',
             'name': 'Net generation : all solar : West Virginia : all sectors '
                     ': annual',
             'series_id': 'ELEC.GEN.TSN-WV-99.A',
             'source': 'EIA, U.S. Energy Information Administration',
             'start': '2014',
             'units': 'thousand megawatthours',
             'updated': '2018-12-24T15:04:35-0500'}]}

In [9]:
# for coal production - State wise
alabama_annual_cow = state_id_to_json('ELEC.GEN.COW-AL-99.A')
alaska_annual_cow = state_id_to_json('ELEC.GEN.COW-AK-99.A')
arizona_annual_cow = state_id_to_json('ELEC.GEN.COW-AZ-99.A')
arkansa_annual_cow = state_id_to_json('ELEC.GEN.COW-AR-99.A')
cali_annual_cow = state_id_to_json('ELEC.GEN.COW-CA-99.A')
colorado_annual_cow = state_id_to_json('ELEC.GEN.COW-CO-99.A')
connecticut_annual_cow = state_id_to_json('ELEC.GEN.COW-CT-99.A')
delaware_annual_cow = state_id_to_json('ELEC.GEN.COW-DE-99.A')
florida_annual_cow = state_id_to_json('ELEC.GEN.COW-FL-99.A')
georgia_annual_cow = state_id_to_json('ELEC.GEN.COW-GA-99.A')
hawaii_annual_cow = state_id_to_json('ELEC.GEN.COW-DE-HI.A')
idaho_annual_cow = state_id_to_json('ELEC.GEN.COW-ID-99.A')
illinois_annual_cow = state_id_to_json('ELEC.GEN.COW-IL-99.A')
indiana_annual_cow = state_id_to_json('ELEC.GEN.COW-IN-99.A')
iowa_annual_cow = state_id_to_json('ELEC.GEN.COW-IA-99.A')
kansas_annual_cow = state_id_to_json('ELEC.GEN.COW-KS-99.A')
ken_annual_cow = state_id_to_json('ELEC.GEN.COW-KY-99.A')
lou_annual_cow = state_id_to_json('ELEC.GEN.COW-LA-99.A')
maine_annual_cow = state_id_to_json('ELEC.GEN.COW-ME-99.A')
maryland_annual_cow = state_id_to_json('ELEC.GEN.COW-MD-99.A')
massa_annual_cow = state_id_to_json('ELEC.GEN.COW-MA-99.A')
michigan_annual_cow = state_id_to_json('ELEC.GEN.COW-MI-99.A')
minnesota_annual_cow = state_id_to_json('ELEC.GEN.COW-MN-99.A')
missis_annual_cow = state_id_to_json('ELEC.GEN.COW-MS-99.A')
missouri_annual_cow = state_id_to_json('ELEC.GEN.COW-MO-99.A')
montana_annual_cow = state_id_to_json('ELEC.GEN.COW-MT-99.A')
neb_annual_cow = state_id_to_json('ELEC.GEN.COW-NB-99.A')
nevada_annual_cow = state_id_to_json('ELEC.GEN.COW-NV-99.A')
newHem_annual_cow = state_id_to_json('ELEC.GEN.COW-NH-99.A')
newJer_annual_cow = state_id_to_json('ELEC.GEN.COW-NJ-99.A')
newMex_annual_cow = state_id_to_json('ELEC.GEN.COW-NM-99.A')
newYork_annual_cow = state_id_to_json('ELEC.GEN.COW-NY-99.A')
norCaro_annual_cow = state_id_to_json('ELEC.GEN.COW-NC-99.A')
norDak_annual_cow = state_id_to_json('ELEC.GEN.COW-ND-99.A')
ohio_annual_cow = state_id_to_json('ELEC.GEN.COW-OH-99.A')
oklo_annual_cow = state_id_to_json('ELEC.GEN.COW-OK-99.A')
oregon_annual_cow = state_id_to_json('ELEC.GEN.COW-OR-99.A')
pennsil_annual_cow = state_id_to_json('ELEC.GEN.COW-PA-99.A')
souCaro_annual_cow = state_id_to_json('ELEC.GEN.COW-SC-99.A')
souDak_annual_cow = state_id_to_json('ELEC.GEN.COW-SD-99.A')
ten_annual_cow = state_id_to_json('ELEC.GEN.COW-TN-99.A')
texas_annual_cow = state_id_to_json('ELEC.GEN.COW-TX-99.A')
utah_annual_cow = state_id_to_json('ELEC.GEN.COW-UT-99.A')
virginia_annual_cow = state_id_to_json('ELEC.GEN.COW-VA-99.A')
wash_annual_cow = state_id_to_json('ELEC.GEN.COW-WA-99.A')
westvir_annual_cow = state_id_to_json('ELEC.GEN.COW-WV-99.A')
wisc_annual_cow = state_id_to_json('ELEC.GEN.COW-WI-99.A')
wyom_annual_cow = state_id_to_json('ELEC.GEN.COW-WY-99.A')

pprint(virginia_annual_cow)

{'request': {'command': 'series', 'series_id': 'ELEC.GEN.COW-VA-99.A'},
 'series': [{'copyright': 'None',
             'data': [['2017', 10726.42243],
                      ['2016', 16499.41236],
                      ['2015', 17231.42569],
                      ['2014', 20818.58432],
                      ['2013', 21160.50127],
                      ['2012', 14180.79527],
                      ['2011', 19881.11344],
                      ['2010', 25459.2208],
                      ['2009', 25599.28782],
                      ['2008', 31776.35595],
                      ['2007', 35420.74627],
                      ['2006', 34288.14069],
                      ['2005', 35424.87524],
                      ['2004', 35656.00633],
                      ['2003', 37093.331],
                      ['2002', 38082.381],
                      ['2001', 37769.911]],
             'description': 'Summation of all types of coal; All sectors; ',
             'end': '2017',
             'f': 'A',
             'geography': 'USA-VA',
             'iso3166': 'USA-VA',
             'name': 'Net generation : coal : Virginia : all sectors : annual',
             'series_id': 'ELEC.GEN.COW-VA-99.A',
             'source': 'EIA, U.S. Energy Information Administration',
             'start': '2001',
             'units': 'thousand megawatthours',
             'updated': '2018-12-24T15:04:35-0500'}]}

In [16]:
# for nuclear production - State wise
alabama_annual_nuc = state_id_to_json('ELEC.GEN.NUC-AL-99.A')
arizona_annual_nuc = state_id_to_json('ELEC.GEN.NUC-AZ-99.A')
arkansa_annual_nuc = state_id_to_json('ELEC.GEN.NUC-AR-99.A')
cali_annual_nuc = state_id_to_json('ELEC.GEN.NUC-CA-99.A')
connecticut_annual_nuc = state_id_to_json('ELEC.GEN.NUC-CT-99.A')
florida_annual_nuc = state_id_to_json('ELEC.GEN.NUC-FL-99.A')
georgia_annual_nuc = state_id_to_json('ELEC.GEN.NUC-GA-99.A')
illinois_annual_nuc = state_id_to_json('ELEC.GEN.NUC-IL-99.A')
iowa_annual_nuc = state_id_to_json('ELEC.GEN.NUC-IA-99.A')
kansas_annual_nuc = state_id_to_json('ELEC.GEN.NUC-KS-99.A')
lou_annual_nuc = state_id_to_json('ELEC.GEN.NUC-LA-99.A')
maryland_annual_nuc = state_id_to_json('ELEC.GEN.NUC-MD-99.A')
massa_annual_nuc = state_id_to_json('ELEC.GEN.NUC-MA-99.A')
michigan_annual_nuc = state_id_to_json('ELEC.GEN.NUC-MI-99.A')
minnesota_annual_nuc = state_id_to_json('ELEC.GEN.NUC-MN-99.A')
missis_annual_nuc = state_id_to_json('ELEC.GEN.NUC-MS-99.A')
missouri_annual_nuc = state_id_to_json('ELEC.GEN.NUC-MO-99.A')
neb_annual_nuc = state_id_to_json('ELEC.GEN.NUC-NB-99.A')
newHem_annual_nuc = state_id_to_json('ELEC.GEN.NUC-NH-99.A')
newJer_annual_nuc = state_id_to_json('ELEC.GEN.NUC-NJ-99.A')
newYork_annual_nuc = state_id_to_json('ELEC.GEN.NUC-NY-99.A')
norCaro_annual_nuc = state_id_to_json('ELEC.GEN.NUC-NC-99.A')
ohio_annual_nuc = state_id_to_json('ELEC.GEN.NUC-OH-99.A')
pennsil_annual_nuc = state_id_to_json('ELEC.GEN.NUC-PA-99.A')
souCaro_annual_nuc = state_id_to_json('ELEC.GEN.NUC-SC-99.A')
ten_annual_nuc = state_id_to_json('ELEC.GEN.NUC-TN-99.A')
texas_annual_nuc = state_id_to_json('ELEC.GEN.NUC-TX-99.A')
vermont_annual_nuc = state_id_to_json('ELEC.GEN.NUC-VT-99.A')
virginia_annual_nuc = state_id_to_json('ELEC.GEN.NUC-VA-99.A')
wash_annual_nuc = state_id_to_json('ELEC.GEN.NUC-WA-99.A')
wisc_annual_nuc = state_id_to_json('ELEC.GEN.NUC-WI-99.A')

pprint(texas_annual_nuc)

{'request': {'command': 'series', 'series_id': 'ELEC.GEN.NUC-TX-99.A'},
 'series': [{'copyright': 'None',
             'data': [['2017', 38581.401],
                      ['2016', 42079.445],
                      ['2015', 39354.677],
                      ['2014', 39287.443],
                      ['2013', 38314.996],
                      ['2012', 38441.017],
                      ['2011', 39648.457],
                      ['2010', 41335.248],
                      ['2009', 41497.617],
                      ['2008', 40727.37],
                      ['2007', 40955.03],
                      ['2006', 41264.278],
                      ['2005', 38232.493],
                      ['2004', 40435.372],
                      ['2003', 33437.484],
                      ['2002', 35618.004],
                      ['2001', 38162.863]],
             'description': 'Nuclear fuel; All sectors; ',
             'end': '2017',
             'f': 'A',
             'geography': 'USA-TX',
             'iso3166': 'USA-TX',
             'name': 'Net generation : nuclear : Texas : all sectors : annual',
             'series_id': 'ELEC.GEN.NUC-TX-99.A',
             'source': 'EIA, U.S. Energy Information Administration',
             'start': '2001',
             'units': 'thousand megawatthours',
             'updated': '2018-12-24T15:04:35-0500'}]}

In [17]:
# for natural gas production - State wise
alabama_annual_ng = state_id_to_json('ELEC.GEN.NG-AL-99.A')
alaska_annual_ng = state_id_to_json('ELEC.GEN.NG-AK-99.A')
arizona_annual_ng = state_id_to_json('ELEC.GEN.NG-AZ-99.A')
arkansa_annual_ng = state_id_to_json('ELEC.GEN.NG-AR-99.A')
cali_annual_ng = state_id_to_json('ELEC.GEN.NG-CA-99.A')
colorado_annual_ng = state_id_to_json('ELEC.GEN.NG-CO-99.A')
connecticut_annual_ng = state_id_to_json('ELEC.GEN.NG-CT-99.A')
delaware_annual_ng = state_id_to_json('ELEC.GEN.NG-DE-99.A')
florida_annual_ng = state_id_to_json('ELEC.GEN.NG-FL-99.A')
georgia_annual_ng = state_id_to_json('ELEC.GEN.NG-GA-99.A')
idaho_annual_ng = state_id_to_json('ELEC.GEN.NG-ID-99.A')
illinois_annual_ng = state_id_to_json('ELEC.GEN.NG-IL-99.A')
indiana_annual_ng = state_id_to_json('ELEC.GEN.NG-IN-99.A')
iowa_annual_ng = state_id_to_json('ELEC.GEN.NG-IA-99.A')
kansas_annual_ng = state_id_to_json('ELEC.GEN.NG-KS-99.A')
ken_annual_ng = state_id_to_json('ELEC.GEN.NG-KY-99.A')
lou_annual_ng = state_id_to_json('ELEC.GEN.NG-LA-99.A')
maine_annual_ng = state_id_to_json('ELEC.GEN.NG-ME-99.A')
maryland_annual_ng = state_id_to_json('ELEC.GEN.NG-MD-99.A')
massa_annual_ng = state_id_to_json('ELEC.GEN.NG-MA-99.A')
michigan_annual_ng = state_id_to_json('ELEC.GEN.NG-MI-99.A')
minnesota_annual_ng = state_id_to_json('ELEC.GEN.NG-MN-99.A')
missis_annual_ng = state_id_to_json('ELEC.GEN.NG-MS-99.A')
missouri_annual_ng = state_id_to_json('ELEC.GEN.NG-MO-99.A')
montana_annual_ng = state_id_to_json('ELEC.GEN.NG-MT-99.A')
neb_annual_ng = state_id_to_json('ELEC.GEN.NG-NB-99.A')
nevada_annual_ng = state_id_to_json('ELEC.GEN.NG-NV-99.A')
newHem_annual_ng = state_id_to_json('ELEC.GEN.NG-NH-99.A')
newJer_annual_ng = state_id_to_json('ELEC.GEN.NG-NJ-99.A')
newMex_annual_ng = state_id_to_json('ELEC.GEN.NG-NM-99.A')
newYork_annual_ng = state_id_to_json('ELEC.GEN.NG-NY-99.A')
norCaro_annual_ng = state_id_to_json('ELEC.GEN.NG-NC-99.A')
norDak_annual_ng = state_id_to_json('ELEC.GEN.NG-ND-99.A')
ohio_annual_ng = state_id_to_json('ELEC.GEN.NG-OH-99.A')
oklo_annual_ng = state_id_to_json('ELEC.GEN.NG-OK-99.A')
oregon_annual_ng = state_id_to_json('ELEC.GEN.NG-OR-99.A')
pennsil_annual_ng = state_id_to_json('ELEC.GEN.NG-PA-99.A')
rhodeIsland_annual_ng = state_id_to_json('ELEC.GEN.NG-RI-99.A')
souCaro_annual_ng = state_id_to_json('ELEC.GEN.NG-SC-99.A')
souDak_annual_ng = state_id_to_json('ELEC.GEN.NG-SD-99.A')
ten_annual_ng = state_id_to_json('ELEC.GEN.NG-TN-99.A')
texas_annual_ng = state_id_to_json('ELEC.GEN.NG-TX-99.A')
utah_annual_ng = state_id_to_json('ELEC.GEN.NG-UT-99.A')
vermont_annual_ng = state_id_to_json('ELEC.GEN.NG-VT-99.A')
virginia_annual_ng = state_id_to_json('ELEC.GEN.NG-VA-99.A')
wash_annual_ng = state_id_to_json('ELEC.GEN.NG-WA-99.A')
westvir_annual_ng = state_id_to_json('ELEC.GEN.NG-WV-99.A')
wisc_annual_ng = state_id_to_json('ELEC.GEN.NG-WI-99.A')
wyom_annual_ng = state_id_to_json('ELEC.GEN.NG-WY-99.A')

pprint(souCaro_annual_ng)

{'request': {'command': 'series', 'series_id': 'ELEC.GEN.NG-SC-99.A'},
 'series': [{'copyright': 'None',
             'data': [['2017', 17156.33542],
                      ['2016', 16366.85418],
                      ['2015', 16549.30625],
                      ['2014', 11406.64003],
                      ['2013', 11834.07418],
                      ['2012', 14331.87879],
                      ['2011', 12936.34259],
                      ['2010', 10927.23746],
                      ['2009', 9780.19264],
                      ['2008', 5728.98791],
                      ['2007', 5964.55849],
                      ['2006', 6068.06078],
                      ['2005', 5414.18307],
                      ['2004', 3797.85798],
                      ['2003', 1662.782],
                      ['2002', 4498.319],
                      ['2001', 1176.114]],
             'description': 'Natural Gas; All sectors; ',
             'end': '2017',
             'f': 'A',
             'geography': 'USA-SC',
             'iso3166': 'USA-SC',
             'name': 'Net generation : natural gas : South Carolina : all '
                     'sectors : annual',
             'series_id': 'ELEC.GEN.NG-SC-99.A',
             'source': 'EIA, U.S. Energy Information Administration',
             'start': '2001',
             'units': 'thousand megawatthours',
             'updated': '2018-12-24T15:04:35-0500'}]}

In [24]:
# Initialize PyMongo to work with MongoDBs
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

# Define database and collection
db_EIA = client.EIA_db
summary_collection = db_EIA.summary
statewise_collection = db_EIA.statewise

In [24]:
# insert dataframe df_annual_allstates into summary collection
summary_collection.insert_many(df_annual_allstates.to_dict('records'))

In [33]:
## - For Alabama, Inserting Wind column & then updating rest
headers = ['Year','Wind (in thousand megawatthours)']
df_al_w = pd.DataFrame(alaska_annual_wind['series'][0]['data'], columns=headers)
df_al_w['State'] = 'AL' 
print(df_al_w)
statewise_collection.insert_many(df_al_w.to_dict('records'))

    Year  Wind (in thousand megawatthours) State
0   2017                         141.68700    AL
1   2016                         169.30100    AL
2   2015                         159.69400    AL
3   2014                         151.95700    AL
4   2013                         145.28900    AL
5   2012                          37.39232    AL
6   2011                          12.44600    AL
7   2010                          12.60700    AL
8   2009                           7.02700    AL
9   2008                           0.06800    AL
10  2007                           1.01200    AL
11  2006                           0.78800    AL
12  2005                           0.58900    AL
13  2003                           0.00000    AL
14  2001                           0.95000    AL

In [34]:
## - For Alabama, Adding Hydroelectric column
headers = ['Year','Hydroelectric (in thousand megawatthours)']
df_al_h = pd.DataFrame(alaska_annual_hyc['series'][0]['data'], columns=headers)
df_al_h['State'] = 'AL' 

for index, row in df_al_h.iterrows():
    statewise_collection.update_many({'Year': row[0]}, {"$set": row.to_dict()}, upsert=True)

    Year  Hydroelectric (in thousand megawatthours) State
0   2017                                 1643.67000    AL
1   2016                                 1659.15200    AL
2   2015                                 1568.92900    AL
3   2014                                 1538.73800    AL
4   2013                                 1435.47943    AL
5   2012                                 1575.04500    AL
6   2011                                 1344.74575    AL
7   2010                                 1433.14139    AL
8   2009                                 1323.74441    AL
9   2008                                 1171.80100    AL
10  2007                                 1291.22300    AL
11  2006                                 1223.60701    AL
12  2005                                 1463.94201    AL
13  2004                                 1498.02001    AL
14  2003                                 1582.53600    AL
15  2002                                 1439.35100    AL
16  2001                                 1345.66500    AL
{'Year': '2017', 'Hydroelectric (in thousand megawatthours)': 1643.67, 'State': 'AL'}
2017
{'Year': '2016', 'Hydroelectric (in thousand megawatthours)': 1659.152, 'State': 'AL'}
2016
{'Year': '2015', 'Hydroelectric (in thousand megawatthours)': 1568.929, 'State': 'AL'}
2015
{'Year': '2014', 'Hydroelectric (in thousand megawatthours)': 1538.738, 'State': 'AL'}
2014
{'Year': '2013', 'Hydroelectric (in thousand megawatthours)': 1435.47943, 'State': 'AL'}
2013
{'Year': '2012', 'Hydroelectric (in thousand megawatthours)': 1575.045, 'State': 'AL'}
2012
{'Year': '2011', 'Hydroelectric (in thousand megawatthours)': 1344.74575, 'State': 'AL'}
2011
{'Year': '2010', 'Hydroelectric (in thousand megawatthours)': 1433.14139, 'State': 'AL'}
2010
{'Year': '2009', 'Hydroelectric (in thousand megawatthours)': 1323.74441, 'State': 'AL'}
2009
{'Year': '2008', 'Hydroelectric (in thousand megawatthours)': 1171.801, 'State': 'AL'}
2008
{'Year': '2007', 'Hydroelectric (in thousand megawatthours)': 1291.223, 'State': 'AL'}
2007
{'Year': '2006', 'Hydroelectric (in thousand megawatthours)': 1223.60701, 'State': 'AL'}
2006
{'Year': '2005', 'Hydroelectric (in thousand megawatthours)': 1463.94201, 'State': 'AL'}
2005
{'Year': '2004', 'Hydroelectric (in thousand megawatthours)': 1498.02001, 'State': 'AL'}
2004
{'Year': '2003', 'Hydroelectric (in thousand megawatthours)': 1582.536, 'State': 'AL'}
2003
{'Year': '2002', 'Hydroelectric (in thousand megawatthours)': 1439.351, 'State': 'AL'}
2002
{'Year': '2001', 'Hydroelectric (in thousand megawatthours)': 1345.665, 'State': 'AL'}
2001

In [35]:
## - For Alabama, Adding Solar column
headers = ['Year','Solar (in thousand megawatthours)']
df_al_t = pd.DataFrame(alaska_annual_tsn['series'][0]['data'], columns=headers)
df_al_t['State'] = 'AL' 

for index, row in df_al_t.iterrows():
    statewise_collection.update_many({'Year': row[0]}, {"$set": row.to_dict()}, upsert=True)

In [37]:
## - For Alabama, Adding Coal column
headers = ['Year','Coal (in thousand megawatthours)']
df_al_c = pd.DataFrame(alaska_annual_cow['series'][0]['data'], columns=headers)
df_al_c['State'] = 'AL' 

for index, row in df_al_c.iterrows():
    statewise_collection.update_many({'Year': row[0]}, {"$set": row.to_dict()}, upsert=True)

In [38]:
## - For Alabama, Adding Natural Gas column
headers = ['Year','Natural Gas (in thousand megawatthours)']
df_al_ng = pd.DataFrame(alaska_annual_ng['series'][0]['data'], columns=headers)
df_al_ng['State'] = 'AL' 

for index, row in df_al_ng.iterrows():
    statewise_collection.update_many({'Year': row[0]}, {"$set": row.to_dict()}, upsert=True)